---
- name: Install tmux and requirements
  become: true
  community.general.pacman:
    name:
      - tmux
      - xsel
    state: present

- name: Add configuration for tmux
  copy:
    src: "{{ tmux_config }}"
    dest: "/home/{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0644"
  with_items: "{{ users }}"

- name: Install tmux plugin manager with git
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ item }}/.tmux/plugins/tpm"
    update: yes
  with_items: "{{ users }}"
