---
# tasks file for tmux
- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: Add configuration for tmux
  copy:
    src: "{{ tmux_config }}"
    dest: "/home/{{ item.name }}/.tmux.conf"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ users }}"

- name: Install tmux plugin manager with git
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ item.name }}/.tmux/plugins/tpm"
    update: yes
  with_items: "{{ users }}"

- name: change ownership of .tmux directory
  file:
    path: "/home/{{ item.name }}/.tmux"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: directory
    recurse: yes
  with_items: "{{ users }}"
