---
# tasks file for tmux
- include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - unbound

- include_tasks: debian.yml
  when: ansible_distribution == "Debian"
  tags:
    - unbound

- include_tasks: debian.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - unbound

- include_tasks: macosx.yml
  when: ansible_distribution == "MacOSX"
  tags:
    - unbound
