---
- name: Install zsh
  community.general.pacman:
    name:
      - zsh
      - fzf
    state: present

- name: change user shell to zsh
  become: yes
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ users }}"

- name: Install oh-my-zsh with git
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "/home/{{ item }}/.oh-my-zsh"
    depth: "1"
    version: master
    update: no
  with_items: "{{ users }}"

- name: Install Meslo font for powerlevel10k
  ansible.legacy.aur:
    name: "ttf-meslo-nerd-font-powerlevel10k"
  become: yes
  become_user: aur_builder

- name: Install powerlevel10k with git
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "/home/{{ item }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: "1"
  with_items: "{{ users }}"

- name: Install zsh-autosuggestions with git
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "/home/{{ item }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: "1"
  with_items: "{{ users }}"

- name: Install zsh-syntax-highlighting with git
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "/home/{{ item }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: "1"
  with_items: "{{ users }}"

- name: Install zsh-completions with git
  git:
    repo: "https://github.com/zsh-users/zsh-completions"
    dest: "/home/{{ item }}/.oh-my-zsh/custom/plugins/zsh-completions"
    depth: "1"
  with_items: "{{ users }}"
