---
# tasks file for zsh
- include_tasks: variables.yml
  tags:
    - unbound


- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: change user shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - install

- name: Install oh-my-zsh with git
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
    depth: "1"
    version: master
    update: no
  diff: false
  tags:
    - install

- name: Install powerlevel10k with git
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: "1"
    version: "master"
  diff: false
  tags:
    - install

- name: Install zsh-autosuggestions with git
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: "1"
    version: master
  diff: false
  tags:
    - install

- name: Install zsh-syntax-highlighting with git
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: "1"
    version: master
  diff: false
  tags:
    - install

- name: Install zsh-completions with git
  git:
    repo: "https://github.com/zsh-users/zsh-completions"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    depth: "1"
    version: master
  diff: false
  tags:
    - install

- name: Install zsh-vi-mode
  git:
    repo: "https://github.com/jeffreytse/zsh-vi-mode"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-vi-mode"
    depth: "1"
    version: master
  diff: false
  tags:
    - install

- name: change ownership of .oh-my-zsh
  file:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory
    recurse: yes

- name: copy dotfile for zsh
  blockinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK for ZSHRC -->"
    block: "{{ lookup('ansible.builtin.template', zsh_template) }}"
    create: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: copy dotfile for zprofile
  blockinfile:
    path: "{{ ansible_user_dir }}/.zprofile"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK for ZSHRC -->"
    block: "{{ lookup('ansible.builtin.template', zprofile_template) }}"
    create: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: copy dotfile for zshenv
  copy:
    src: "{{ zshenv_config }}"
    dest: "{{ ansible_user_dir }}/.zshenv"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
  when: ansible_distribution != "MacOSX"

- name: copy dotfile for powerlevel10k
  copy:
    src: "{{ p10k_config }}"
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: create bin directory
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory
    recurse: yes

- name: copy executables
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/.local/bin/"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0750"
  with_filetree: "{{ zsh_bin_dir }}"
