---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: Define packages
  set_fact:
    zsh_packages: "{{ __zsh_packages | list }}"
  when: (__zsh_packages is defined) and (zsh_packages is not defined)
