---
- name: Add golang ppa
  ansible.builtin.apt_repository:
    repo: ppa:longsleep/golang-backports

- name: Install golang
  ansible.builtin.package:
    name: golang-{{ golang_version }}
    state: present

- name: Add golang to .zshrc
  blockinfile:
    path: "/home/{{ item }}/.zshrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK for GOLANG -->"
    block: |
      # enable go binaries
      export PATH="$PATH:/usr/lib/go-{{ golang_version }}/bin"
  with_items: "{{ users }}"
