---
- name: Create aur_builder user for aur install tasks
  user:
    name: aur_builder
    group: wheel
    create_home: no
    shell: /usr/bin/nologin
    home: /tmp
  become: true

- name: Add user to sudoers
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"
    mode: "0644"
  become: true
