---
# tasks file for testkitchen

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: Install testinfra, paramiko within a user home directory
  pip:
    name:
      - pytest-testinfra
      - paramiko
    extra_args: --user

- name: Install latest available version of {{ kitchen_gems | join(', ') }}
  community.general.gem:
    name: "{{ item }}"
    state: latest
    user_install: yes
  with_items: "{{ kitchen_gems }}"

- name: Add ruby bin to .zshrc
  blockinfile:
    path: "{{ home_dirs }}/{{ item.name }}/.zshrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK for TESTKITCHEN -->"
    block: |
      if which ruby >/dev/null && which gem >/dev/null; then
          PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
      fi
  with_items: "{{ users }}"
