---
# tasks file for vim

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound


- name: copy dotfile for vim
  copy:
    src: "{{ vim_config }}"
    dest: "{{ ansible_user_dir }}/.vimrc"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: copy keybinds dotfile for vim
  copy:
    src: "{{ vim_keybinds }}"
    dest: "{{ ansible_user_dir }}/.vimrc.keybinds"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: Git checkout
  git:
    repo: "{{ vundle }}"
    dest: "{{ ansible_user_dir }}/.vim/bundle/Vundle.vim"
