---
# tasks file for vim

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound


- name: copy dotfile for vim
  copy:
    src: "{{ vim_config }}"
    dest: "{{ home_dirs }}/{{ item.name }}/.vimrc"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ users }}"

- name: copy keybinds dotfile for vim
  copy:
    src: "{{ vim_keybinds }}"
    dest: "{{ home_dirs }}/{{ item.name }}/.vimrc.keybinds"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ users }}"

- name: Git checkout
  git:
    repo: "{{ vundle }}"
    dest: "{{ home_dirs }}/{{ item.name }}/.vim/bundle/Vundle.vim"
  with_items: "{{ users }}"
