---
- name: Install pyenv dependencies
  become: true
  ansible.builtin.package:
    name:
      - git
      - python3-pip
      - python-is-python3
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libffi-dev
    state: present
