---
- name: Install packages with brew
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - pyenv
    - pyenv-virtualenv
    - pyenv-virtualenvwrapper
    - virtualenvwrapper
  tags:
    - install
