---
# tasks file for rbenv
- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: Install ruby-build with git
  git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "{{ ansible_user_dir }}/.rbenv/plugins/ruby-build"
    depth: "1"
    version: master
  diff: false
  environment:
    GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
  when:
    ansible_facts["os_family"] != "Suse"
  tags:
    - install

- name: edit .zshrc
  blockinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK for RBENV -->"
    block: |
      eval "$(rbenv init -)"
    create: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
