---
# tasks file for rbenv

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: edit .zshrc
  lineinfile:
    line: 'eval "$(rbenv init -)"'
    path: "/home/{{ item }}/.zshrc"
  with_items: "{{ users }}"