---
# tasks file for rbenv
- name: Install ruby-build with git
  git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "/home/{{ item }}/.rbenv/plugins/ruby-build"
    depth: "1"
    version: master
  diff: false
  with_items: "{{ users }}"

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: edit .zshrc
  lineinfile:
    line: 'eval "$(rbenv init -)"'
    path: "/home/{{ item }}/.zshrc"
  with_items: "{{ users }}"