---
- name: Add ruby devel repo
  become: true
  community.general.zypper_repository:
    repo: 'https://download.opensuse.org/repositories/devel:languages:ruby:extensions/openSUSE_Tumbleweed/devel:languages:ruby:extensions.repo'
    state: present
    runrefresh: yes
  tags:
    - install

- name: Install rbenv
  become: true
  ansible.builtin.package:
    name:
      - ruby
      - rbenv
      - ruby-devel
    state: present
  tags:
    - install


- name: Install ruby devel pattern
  become: true
  ansible.builtin.package:
    name:
      - devel_ruby
    state: present
    type: pattern
  tags:
    - install
