---
- name: Install rbenv
  become: true
  ansible.builtin.package:
    name:
      - ruby
    state: present


- name: Install ruby devel pattern
  become: true
  ansible.builtin.package:
    name:
      - devel_ruby
    state: present
    type: pattern