- block:
    - name: "end play for unsupported distribution"
      debug:
        msg: >
          This distribution {{ ansible_distribution }} is not supported by this role.
          You can exclude this role by using the tag {{ (ansible_role_name | split('.'))[-1] }}.
          The role ends here.
    - name: End role
      meta: end_batch
