---
# tasks file for terraform


- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

# Provider can be installed from within an main.tf from the registry
#- name: check go version
#  command: go version
#  register: result
#  changed_when: no
#  ignore_errors: true

#- set_fact:
#    go_path: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME + '/go', true) }}"
#  when: result is succeeded

#- name: Get terraform plugins with go
#  shell: go get -v {{ item }}
#  environment:
#    GOPATH: "{{ go_path }}"
#  when: result is succeeded
#  with_items: "{{ terraform_plugins }}"
