---
- name: Install dotfiles and applications
  hosts: all
  vars:
    users:
      - matze
#    tmux_config: "my_tmux.conf"
#    vim_config: "my_vimrc.conf"

  roles:
    - {
        role: mattfoxxx.dotfiles.tmux,
        tags: ["tmux"],
#        vars: { users: ["test"] },
      }
    - {
        role: mattfoxxx.dotfiles.vim,
        tags: ["vim"],
      }
    - {
        role: mattfoxxx.dotfiles.zsh,
        tags: ["zsh"],
      }

  tasks:
    - debug:
        var: users
      tags: debug
    - debug:
        var: tmux_config
      tags: debug
    - debug:
        var: vim_config
      tags: debug

    - name: __________POST INSTALL MESSAGE__________
      debug:
        msg:
          - 'Things left to do:'
          - '- VIM: Execute in vim :PluginInstall'
      tags:
        - always
