---
- name: Install dotfiles and applications
  hosts: all
  vars:
    users:
      - matze
#    tmux_config: "my_tmux.conf"
#    vim_config: "my_vimrc.conf"

  roles:
    - {
        role: mattfoxxx.dotfiles.tmux,
        tags: ["tmux"],
#        vars: { users: ["test"] },
      }
    - {
        role: mattfoxxx.dotfiles.vim,
        tags: ["vim"],
#        vars: { users: ["test"] },
      }

  tasks:
    - name: display variables
      debug:
        var: 
          - users
          - tmux_config
          - vim_config

    - name: display post install message
      debug:
        msg:
          - 'Things left to do:'
          - '- VIM: Execute in vim :PluginInstall'
