---
- name: Install dotfiles and applications
  hosts: all
  remote_user: matze
  vars:
    users:
      - matze
#    tmux_config: "my_tmux.conf"
#    vim_config: "my_vimrc.conf"

  roles:
    - {
        role: mattfoxxx.dotfiles.setup,
        tags: ["setup", "always"],
        when: ansible_distribution == "Archlinux"
      }
    - {
        role: mattfoxxx.dotfiles.tmux,
        tags: ["tmux"],
#        vars: { users: ["test"] },
      }
    - {
        role: mattfoxxx.dotfiles.vim,
        tags: ["vim"],
      }
    - {
        role: mattfoxxx.dotfiles.nvim,
        tags: ["nvim"],
      }
    - {
        role: mattfoxxx.dotfiles.zsh,
        tags: ["zsh"],
      }
    - {
        role: mattfoxxx.dotfiles.rbenv,
        tags: ["rbenv"],
      }
    - {
        role: mattfoxxx.dotfiles.syncthing,
        tags: ["syncthing"],
      }
    - {
        role: mattfoxxx.dotfiles.pyenv,
        tags: ["pyenv"],
      }
    - {
        role: mattfoxxx.dotfiles.testkitchen,
        tags: ["testkitchen"],
      }
    - {
        role: mattfoxxx.dotfiles.golang,
        tags: ["golang", "devops"],
      }
    - {
        role: mattfoxxx.dotfiles.terraform,
        tags: ["terraform", "devops"],
      }
    - {
        role: mattfoxxx.dotfiles.rclone,
        tags: ["rclone", "shell"],
      }

  tasks:
    - name: Debug users var
      debug:
        var: users
      tags: debug
    - name: Debug tmux_config var
      debug:
        var: tmux_config
      tags: debug
    - name: Debug vim_config var
      debug:
        var: vim_config
      tags: debug

    - name: __________POST INSTALL MESSAGE__________
      debug:
        msg:
          - 'Things left to do:'
          - '- TMUX:   use `prefix+I` to install plugins'
          - '- VIM:    Execute in vim :PluginInstall'
          - '- RCLONE: `rclone config` and follow the steps'
          - '  RCLONE: `systemctl --user start rclone.service`'
      tags:
        - always
