---
- name: Install dotfiles and applications
  hosts: all
  remote_user: matze
  vars:
    home_dirs: /Users
    users:
      - name: mintert
        group: staff
  #    tmux_config: "my_tmux.conf"
  #    vim_config: "my_vimrc.conf"

  roles:
    - {
      role: mattfoxxx.dotfiles.setup,
      tags: ["all", "setup", "always"],
      when: ansible_distribution == "Archlinux"
    }
    - {
      role: mattfoxxx.dotfiles.tmux,
      tags: ["all", "tmux"],
      #        vars: { users: ["test"] },
    }
    - {
      role: mattfoxxx.dotfiles.vim,
      tags: ["all", "vim"],
    }
    - {
      role: mattfoxxx.dotfiles.nvim,
      tags: ["all", "nvim"],
    }
    - {
      role: mattfoxxx.dotfiles.zsh,
      tags: ["all", "zsh"],
    }
    - {
      role: mattfoxxx.dotfiles.rbenv,
      tags: ["all", "rbenv"],
    }
    - {
      role: mattfoxxx.dotfiles.syncthing,
      tags: ["all", "syncthing"],
    }
    - {
      role: mattfoxxx.dotfiles.pyenv,
      tags: ["all", "pyenv"],
    }
    - {
      role: mattfoxxx.dotfiles.testkitchen,
      tags: ["all", "testkitchen"],
    }
    - {
      role: mattfoxxx.dotfiles.golang,
      tags: ["all", "golang", "devops"],
    }
    - {
      role: mattfoxxx.dotfiles.terraform,
      tags: ["all", "terraform", "devops"],
    }
    - {
      role: mattfoxxx.dotfiles.rclone,
      tags: ["all", "rclone", "shell"],
    }

  tasks:
    - name: Debug users var
      debug:
        var: users
      tags: debug
    - name: Debug tmux_config var
      debug:
        var: tmux_config
      tags: debug
    - name: Debug vim_config var
      debug:
        var: vim_config
      tags: debug

    - name: __________POST INSTALL MESSAGE__________
      debug:
        msg:
          - 'Things left to do:'
          - '- TMUX:   use `prefix+I` to install plugins'
          - '- VIM:    Execute in vim :PluginInstall'
          - '- RCLONE: `rclone config` and follow the steps'
          - '  RCLONE: `systemctl --user start rclone.service`'
      tags:
        - always
