

"
"                         ███████████████████████████
"                         ███████▀▀▀░░░░░░░▀▀▀███████
"                         ████▀░░░░░░░░░░░░░░░░░▀████
"                         ███│░░░░░░░░░░░░░░░░░░░│███
"                         ██▌│░░░░░░░░░░░░░░░░░░░│▐██
"                         ██░└┐░░░░░░░░░░░░░░░░░┌┘░██
"                         ██░░└┐░░░░░░░░░░░░░░░┌┘░░██
"                         ██░░┌┘▄▄▄▄▄░░░░░▄▄▄▄▄└┐░░██
"                         ██▌░│██████▌░░░▐██████│░▐██
"                         ███░│▐███▀▀░░▄░░▀▀███▌│░███
"                         ██▀─┘░░░░░░░▐█▌░░░░░░░└─▀██
"                         ██▄░░░▄▄▄▓░░▀█▀░░▓▄▄▄░░░▄██
"                         ████▄─┘██▌░░░░░░░▐██└─▄████
"                         █████░░▐█─┬┬┬┬┬┬┬─█▌░░█████
"                         ████▌░░░▀┬┼┼┼┼┼┼┼┬▀░░░▐████
"                         █████▄░░░└┴┴┴┴┴┴┴┘░░░▄█████
"                         ███████▄░░░░░░░░░░░▄███████
"                         ██████████▄▄▄▄▄▄▄██████████
"                         ███████████████████████████
"
"   You are about to experience a potent dosage of Vim. Watch your steps.
"
"                ╔══════════════════════════════════════════╗
"                ║           ⎋ HERE BE VIMPIRES ⎋           ║
"                ╚══════════════════════════════════════════╝
set shell=/bin/zsh "Sets the shell  
set nocompatible "Use the vim settings, not vi
filetype off " required by vundle
if ! executable( 'git' )
    echohl ErrorMsg | echomsg 'Git is not available.' | echohl None
else
    " set the runtime path to include Vundle and initialize
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    " alternatively, pass a path where Vundle should install plugins
    "call vundle#begin('~/some/path/here')

    " Initial setup for vundle
    " $ git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    " let Vundle manage Vundle, required
    Plugin 'VundleVim/Vundle.vim'

	" shows indentation rulers
    Plugin 'Yggdroot/indentLine.git'
	" file explorer
    Plugin 'scrooloose/nerdtree.git'
	" git plugin
    Plugin 'tpope/vim-fugitive.git'
	" better markdown support
    Plugin 'tpope/vim-markdown.git'
    Plugin 'shime/vim-livedown.git'
	" saltstack support
    Plugin 'saltstack/salt-vim.git'
	" fuzzy file finder
    Plugin 'ctrlpvim/ctrlp.vim'
	" python support
    Plugin 'python-mode/python-mode'
	" tmux intergration
    Plugin 'preservim/vimux'
	" source code analysis
    Plugin 'dense-analysis/ale'
	" completion engine
	" Plugin 'ycm-core/YouCompleteMe'

	" visuals
    Plugin 'vim-airline/vim-airline.git'
    Plugin 'vim-airline/vim-airline-themes.git'
    Plugin 'ryanoasis/vim-devicons.git'
    Plugin 'airblade/vim-gitgutter.git'
    Plugin 'powerline/fonts.git'
	Plugin 'micha/vim-colors-solarized'
    Plugin 'sickill/vim-monokai'
    Plugin 'arcticicestudio/nord-vim'

    " All of your Plugins must be added before the following line
    call vundle#end()            " required
endif

filetype plugin on "Enables the recognition files 
filetype indent on


so ~/.vimrc.keybinds


" ########################################
" ################ PLUGINS ###############
" ########################################

" NerdTree {
if isdirectory(expand("~/.vim/bundle/nerdtree"))
	map <C-e> :NERDTreeToggle<CR>
	map <leader>e :NERDTreeFind<CR>
	nmap <leader>nt :NERDTreeFind<CR>

	let NERDTreeShowBookmarks=1
	let NERDTreeIgnore=['\.py[cd]$', '\~$', '\.swo$', '\.swp$', '^\.git$', '^\.hg$','^\.svn$', '\.bzr$']
	let NERDTreeChDirMode=0
	let NERDTreeQuitOnOpen=1
	let NERDTreeMouseMode=2
	let NERDTreeShowHidden=1
	let NERDTreeKeepTreeInNewTab=1
	let g:nerdtree_tabs_open_on_gui_startup=0
endif
      " }

"Vim-airline
let g:airline_theme = 'luna'
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
"Vim-airline
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
"let g:airline_symbols.space = "\ua0"

if !exists('g:airline_powerline_fonts')
  let g:airline#extensions#tabline#left_sep = ' '
  let g:airline#extensions#tabline#left_alt_sep = '|'
  let g:airline_left_sep          = '▶'
  let g:airline_left_alt_sep      = '»'
  let g:airline_right_sep         = '◀'
  let g:airline_right_alt_sep     = '«'
  let g:airline#extensions#branch#prefix     = '⤴' "➔, ➥, ⎇
  let g:airline#extensions#readonly#symbol   = '⊘'
  let g:airline#extensions#linecolumn#prefix = '¶'
  let g:airline#extensions#paste#symbol      = 'ρ'
  let g:airline_symbols.linenr    = '␊'
  let g:airline_symbols.branch    = '⎇'
  let g:airline_symbols.paste     = 'ρ'
  let g:airline_symbols.paste     = 'Þ'
  let g:airline_symbols.paste     = '∥'
  let g:airline_symbols.whitespace = 'Ξ'
else
  let g:airline#extensions#tabline#left_sep = ''
  let g:airline#extensions#tabline#left_alt_sep = ''

  " powerline symbols
  let g:airline_left_sep = ''
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ''
  let g:airline_right_alt_sep = ''
  let g:airline_symbols.branch = ''
  let g:airline_symbols.readonly = ''
  let g:airline_symbols.linenr = ''
endif


"" Settings for python-mode
" map <Leader>g :call RopeGotoDefinition()<CR>
" let ropevim_enable_shortcuts = 1
" let g:pymode_rope_goto_def_newwin = "vnew"
" let g:pymode_rope_extended_complete = 1
" let g:pymode_breakpoint = 0
" let g:pymode_syntax = 1
" let g:pymode_syntax_builtin_objs = 0
" let g:pymode_syntax_builtin_funcs = 0
" "map <Leader>b Oimport ipdb; ipdb.set_trace() # BREAKPOINT<C-c>

" Vim-gitgutter
let g:gitgutter_override_sign_column_highlight = 0
highlight SignColumn ctermbg=237
" let g:gitgutter_sign_column_always = 1
set signcolumn=yes
let g:gitgutter_sign_added = 'xx'
let g:gitgutter_sign_modified = 'yy'
let g:gitgutter_sign_removed = 'zz'
let g:gitgutter_sign_removed_first_line = '^^'
let g:gitgutter_sign_modified_removed = 'ww'

" vim-livedown
nmap gm :LivedownToggle<CR>
let g:livedown_autorun = 0 " should markdown preview get shown automatically upon opening markdown buffer
let g:livedown_open = 1 " should the browser window pop-up upon previewing
let g:livedown_port = 11337 " the port on which Livedown server will run
let g:livedown_browser = "firefox" " the system command to launch a browser (ex. on linux)
"let g:livedown_browser = "open /Applications/Firefox.app"

" nnoremap [1;5D B
" nnoremap [1;5C W
" set t_Co=256
" set term=xterm-256color

"" YouCompleteMe
"let g:ycm_global_ycm_extra_conf='~/.vim/bundle/YouCompleteMe/.ycm_extra_conf.py'
"let g:ycm_confirm_extra_conf=0
"let g:ycm_python_binary_path='/usr/bin/python3'
