---
# tasks file for rclone

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound

- name: Create directory for systemd unit
  file:
    state: directory
    path: "{{ ansible_user_dir }}/.config/systemd/user/"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create user systemd unit for rclone
  template:
    src: rclone.service.jinja
    dest: "{{ ansible_user_dir }}/.config/systemd/user/rclone.service"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0640

- name: Check if config file exists
  ansible.builtin.shell: test -e ~/.config/rclone/rclone.conf && echo true || echo false
  args:
    executable: /bin/bash
  changed_when: false
  register: rclone_conf_exists

- name: Enable systemd user unit
  systemd:
    enabled: yes
    daemon_reload: yes
    name: rclone
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}"
  when: rclone_conf_exists | bool

- name: Start systemd user unit
  systemd:
    state: restarted
    name: rclone
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}"
  when: rclone_conf_exists | bool
