---
# tasks file for rclone

- include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - unbound

- include_tasks: debian.yml
  when: ansible_distribution == "Debian"
  tags:
    - unbound

- include_tasks: debian.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - unbound
#- include_tasks: redhat.yml
#  when: ansible_os_family == "RedHat"
#  tags:
#    - unbound

- name: Create directory for systemd unit
  file:
    state: directory
    path: "/home/{{ ansible_user }}/.config/systemd/user/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create user systemd unit for rclone
  template:
    src: rclone.service.jinja
    dest: "/home/{{ ansible_user }}/.config/systemd/user/rclone.service"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640

- name: Enable systemd user unit
  systemd:
    enabled: yes
    daemon_reload: yes
    name: rclone
    scope: user
  ignore_errors: true

- raw: test -e ~/.config/rclone/rclone.conf && echo true || echo false
  register: rclone_conf_exists

- name: Start systemd user unit
  systemd:
    state: restarted
    name: rclone
    scope: user
  when: rclone_conf_exists
