---
# tasks file for vim

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound


- name: copy dotfile for nvim
  copy:
    src: "{{ nvim_config }}"
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"


- name: copy mardown preview dotfile for nvim
  copy:
    src: "mkdp.vim"
    dest: "{{ ansible_user_dir }}/.config/nvim/mkdp.vim"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"


- name: Create lua directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim/lua"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0750"
    state: directory


- name: copy lua dir for nvim
  synchronize:
    src: "{{ nvim_lua_dir }}"
    dest: "{{ ansible_user_dir }}/.config/nvim/lua/"
    recursive: yes

- name: Create vim plug directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0750"
    state: directory


- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/plug.vim"
    mode: '0644'
  tags:
    - install
