---
# tasks file for vim

- name: Include os specific tasks
  include_tasks: "{{ distro_item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: distro_item
  tags:
    - unbound


- name: copy dotfile for nvim
  copy:
    src: "{{ nvim_config }}"
    dest: "{{ home_dirs }}/{{ item.name }}/.config/nvim/init.vim"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ users }}"


- name: copy mardown preview dotfile for nvim
  copy:
    src: "mkdp.vim"
    dest: "{{ home_dirs }}/{{ item.name }}/.config/nvim/mkdp.vim"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ users }}"


- name: Create lua directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ home_dirs }}/{{ item.name }}/.config/nvim/lua"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0750"
    state: directory
  with_items: "{{ users }}"


- name: copy lua dir for nvim
  synchronize:
    src: "{{ nvim_lua_dir }}"
    dest: "{{ home_dirs }}/{{ item.name }}/.config/nvim/lua/"
    recursive: yes
  with_items: "{{ users }}"

    #- name: copy lua dir for nvim
    #  copy:
    #    src: "{{ nvim_lua_dir }}"
    #    dest: "{{ home_dirs }}/{{ item.name }}/.config/nvim/lua/"
    #    owner: "{{ item.name }}"
    #    group: "{{ item.group }}"
    #    mode: "0644"
    #    remote_src: yes
    #    directory_mode: yes
    #  with_items: "{{ users }}"

- name: Create vim plug directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ home_dirs }}/{{ item.name }}/.local/share/nvim/site/autoload/"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "0750"
    state: directory
  with_items: "{{ users }}"


- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home_dirs }}/{{ item.name }}/.local/share/nvim/site/autoload/plug.vim"
    mode: '0644'
  with_items: "{{ users }}"
